WELCOME TO CRESENCIO'S LAB 6: NUMERICAL AND DATA ANAYLSIS WITH NUMPY AND PANDAS

START OF PROCEDURE OF LAB 6

In [176]:
# PROCEDURE 1: Creating NumPy Arrays

# Step 1: Import NumPy
import numpy as np

# Step 2: Create a 1D array representing years of experience
years_exp = np.array([1, 3, 5, 7, 10])
print("Years of Experience:", years_exp)

# Step 3: Create a 2D array representing sample salaries (in thousands)
salaries = np.array([[50, 60, 70], [80, 90, 100]])
print("Salary Matrix:\n", salaries)

# Step 4: Create an array of zeros and ones for placeholder analysis
zeros_array = np.zeros((2, 2))  # 2x2 zeros
ones_array = np.ones((2, 3))    # 2x3 ones
print("Zeros Array:\n", zeros_array)
print("Ones Array:\n", ones_array)

Years of Experience: [ 1  3  5  7 10]
Salary Matrix:
 [[ 50  60  70]
 [ 80  90 100]]
Zeros Array:
 [[0. 0.]
 [0. 0.]]
Ones Array:
 [[1. 1. 1.]
 [1. 1. 1.]]


In [177]:
# TRY IT - Procedure 1

# Add 2 more sample data points to years_exp and salaries
years_exp = np.array([1, 3, 5, 7, 10, 12, 15])
print("Updated Years of Experience:", years_exp)

salaries = np.array([[50, 60, 70], [80, 90, 100], [110, 120, 130]])
print("Updated Salary Matrix:\n", salaries)

# Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print("3x3 Identity Matrix:\n", identity_matrix)

Updated Years of Experience: [ 1  3  5  7 10 12 15]
Updated Salary Matrix:
 [[ 50  60  70]
 [ 80  90 100]
 [110 120 130]]
3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [178]:
# PROCEDURE 2: Array Operations

import numpy as np
years_exp = np.array([1, 3, 5, 7, 10])

# Step 1: Element-wise addition
exp_plus_5 = years_exp + 5  # Add 5 years to all experience values
print("Years + 5:", exp_plus_5)

# Step 2: Element-wise multiplication
exp_times_2 = years_exp * 2  # Multiply all values by 2
print("Years * 2:", exp_times_2)

# Step 3: Dot product (simulate salary projections)
sample1 = np.array([1, 2, 3])
sample2 = np.array([4, 5, 6])
dot_result = np.dot(sample1, sample2)
print("Dot Product:", dot_result)

Years + 5: [ 6  8 10 12 15]
Years * 2: [ 2  6 10 14 20]
Dot Product: 32


In [179]:
# TRY IT - Procedure 2

# Subtraction and division
print("Years - 2:", years_exp - 2)
print("Years / 2:", years_exp / 2)

# Apply np.exp() and np.log() on arrays
print("np.exp(years_exp):", np.exp(years_exp))
print("np.log(years_exp):", np.log(years_exp))

Years - 2: [-1  1  3  5  8]
Years / 2: [0.5 1.5 2.5 3.5 5. ]
np.exp(years_exp): [2.71828183e+00 2.00855369e+01 1.48413159e+02 1.09663316e+03
 2.20264658e+04]
np.log(years_exp): [0.         1.09861229 1.60943791 1.94591015 2.30258509]


In [180]:
# PROCEDURE 3: Indexing and Slicing

import numpy as np
years_exp = np.array([1, 3, 5, 7, 10])
salaries = np.array([[50, 60, 70], [80, 90, 100]])

# Step 1: Access individual element
print("First year of experience:", years_exp[0])

# Step 2: Slice arrays
print("First two salaries:", salaries[0, :2])  # First two elements of first row

# Step 3: Access all rows for a specific column
print("Second column salaries:", salaries[:, 1])

# Step 4: Negative indexing
print("Last year of experience:", years_exp[-1])

First year of experience: 1
First two salaries: [50 60]
Second column salaries: [60 90]
Last year of experience: 10


In [181]:
# TRY IT - Procedure 3

# Reverse arrays using slicing
print("Reversed years_exp:", years_exp[::-1])

# Slice 2D arrays for subgroups of salaries
print("Last two columns of salaries:\n", salaries[:, 1:])
print("Reversed salaries matrix:\n", salaries[::-1, ::-1])

Reversed years_exp: [10  7  5  3  1]
Last two columns of salaries:
 [[ 60  70]
 [ 90 100]]
Reversed salaries matrix:
 [[100  90  80]
 [ 70  60  50]]


In [182]:
# PROCEDURE 4: Reshaping and Dimensions

import numpy as np

# Step 1: Reshape 1D array into 2x3 matrix for batch analysis
reshaped_exp = np.reshape(np.arange(1, 7), (2, 3))
print("Reshaped Experience Array:\n", reshaped_exp)

# Step 2: Flatten 2D arrays back into 1D
flattened_exp = reshaped_exp.flatten()
print("Flattened Array:", flattened_exp)

# Step 3: Transpose example
print("Transposed Array:\n", reshaped_exp.T)

Reshaped Experience Array:
 [[1 2 3]
 [4 5 6]]
Flattened Array: [1 2 3 4 5 6]
Transposed Array:
 [[1 4]
 [2 5]
 [3 6]]


In [183]:
# TRY IT - Procedure 4

# Reshape into different dimensions using a real dataset
data = np.arange(1, 25)  # 24 elements

reshaped_3x8 = data.reshape(3, 8)
print("Reshaped 3x8:\n", reshaped_3x8)

reshaped_4x6 = data.reshape(4, 6)
print("Reshaped 4x6:\n", reshaped_4x6)

reshaped_2x3x4 = data.reshape(2, 3, 4)
print("Reshaped 2x3x4:\n", reshaped_2x3x4)

Reshaped 3x8:
 [[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]]
Reshaped 4x6:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
Reshaped 2x3x4:
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [184]:
# PROCEDURE 5: Broadcasting in NumPy

import numpy as np
salaries = np.array([[50, 60, 70], [80, 90, 100]])

# Step 1: Add a bonus array to salaries using broadcasting
bonus = np.array([5, 10, 15])
salaries_with_bonus = salaries + bonus  # Adds corresponding bonus to each column
print("Salaries after bonus:\n", salaries_with_bonus)

Salaries after bonus:
 [[ 55  70  85]
 [ 85 100 115]]


In [185]:
# TRY IT - Procedure 5

# Multiply salaries by a scaling factor using broadcasting
scaling_factor = np.array([1.1, 1.2, 1.3])
salaries_scaled = salaries * scaling_factor
print("Salaries after scaling:\n", salaries_scaled)

# Broadcast a column vector
raise_factor = np.array([[1.05], [1.10]])
salaries_raised = salaries * raise_factor
print("Salaries with row-wise raise:\n", salaries_raised)

Salaries after scaling:
 [[ 55.  72.  91.]
 [ 88. 108. 130.]]
Salaries with row-wise raise:
 [[ 52.5  63.   73.5]
 [ 88.   99.  110. ]]


In [186]:
# PROCEDURE 6: Statistical Operations

import numpy as np
years_exp = np.array([1, 3, 5, 7, 10])
salaries = np.array([[50, 60, 70], [80, 90, 100]])

# Step 1: Mean of years of experience
print("Mean experience:", np.mean(years_exp))

# Step 2: Standard deviation of experience
print("Std deviation of experience:", np.std(years_exp))

# Step 3: Max and Min salaries
print("Max salary:", np.max(salaries), "Min salary:", np.min(salaries))

# Step 4: Sum of salaries
print("Sum of all salaries:", np.sum(salaries))

Mean experience: 5.2
Std deviation of experience: 3.1240998703626617
Max salary: 100 Min salary: 50
Sum of all salaries: 450


In [187]:
# TRY IT - Procedure 6

# Compute median and percentiles for arrays
print("Median experience:", np.median(years_exp))
print("25th percentile:", np.percentile(years_exp, 25))
print("75th percentile:", np.percentile(years_exp, 75))
print("90th percentile:", np.percentile(years_exp, 90))

Median experience: 5.0
25th percentile: 3.0
75th percentile: 7.0
90th percentile: 8.8


In [188]:
# PROCEDURE 7: NumPy Functions on Arrays

import numpy as np
salaries = np.array([[50, 60, 70], [80, 90, 100]])

# Step 1: Apply trigonometric functions
angles = np.array([0, np.pi/4, np.pi/2])
print("Sine of angles:", np.sin(angles))
print("Cosine of angles:", np.cos(angles))

# Step 2: Apply function along rows (sum salaries per person)
salary_sums = np.apply_along_axis(np.sum, 1, salaries)
print("Sum of Salaries per person:", salary_sums)

Sine of angles: [0.         0.70710678 1.        ]
Cosine of angles: [1.00000000e+00 7.07106781e-01 6.12323400e-17]
Sum of Salaries per person: [180 270]


In [189]:
# TRY IT - Procedure 7

import numpy as np
arr = np.array([1, 4, 9, 16, 25])

# Use np.sqrt() and np.log() for transformations
print("Square roots:", np.sqrt(arr))
print("Natural log:", np.log(arr))

# Apply a custom function with np.apply_along_axis()
salaries = np.array([[50, 60, 70], [80, 90, 100]])

def salary_range(row):
    return np.max(row) - np.min(row)

salary_ranges = np.apply_along_axis(salary_range, 1, salaries)
print("Salary range per person:", salary_ranges)

Square roots: [1. 2. 3. 4. 5.]
Natural log: [0.         1.38629436 2.19722458 2.77258872 3.21887582]
Salary range per person: [20 20]


In [190]:
# PROCEDURE 8: Integrating NumPy and Pandas

import numpy as np
import pandas as pd

# Step 1: Create a NumPy array of random data
data = np.random.randint(1, 50, size=(5, 3))

# Step 2: Convert the array into a DataFrame
df_data = pd.DataFrame(data, columns=['X', 'Y', 'Z'])
print("Generated Data:\n", df_data)

# Step 3: Apply NumPy functions to DataFrame columns
df_data['Log_X'] = np.log(df_data['X'])
df_data['Sqrt_Y'] = np.sqrt(df_data['Y'])
print("DataFrame with NumPy Transformations:\n", df_data)

# Step 4: Analyze data using Pandas correlation
print("Correlation Matrix:\n", df_data.corr())

Generated Data:
     X   Y   Z
0  10  13   8
1   4  46   7
2  20  44  41
3  41   2  49
4  36  46  21
DataFrame with NumPy Transformations:
     X   Y   Z     Log_X    Sqrt_Y
0  10  13   8  2.302585  3.605551
1   4  46   7  1.386294  6.782330
2  20  44  41  2.995732  6.633250
3  41   2  49  3.713572  1.414214
4  36  46  21  3.583519  6.782330
Correlation Matrix:
                X         Y         Z     Log_X    Sqrt_Y
X       1.000000 -0.310444  0.730719  0.957806 -0.395058
Y      -0.310444  1.000000 -0.316948 -0.300047  0.990449
Z       0.730719 -0.316948  1.000000  0.756060 -0.404669
Log_X   0.957806 -0.300047  0.756060  1.000000 -0.359027
Sqrt_Y -0.395058  0.990449 -0.404669 -0.359027  1.000000


In [191]:
# TRY IT - Procedure 8

import numpy as np
import pandas as pd

# Use np.mean() and np.median() to compute overall column statistics
data = np.random.randint(1, 50, size=(5, 3))
df_data = pd.DataFrame(data, columns=['X', 'Y', 'Z'])

print("Column Means (NumPy):", np.mean(df_data[['X','Y','Z']].values, axis=0))
print("Column Medians (NumPy):", np.median(df_data[['X','Y','Z']].values, axis=0))

# Apply np.square() and np.exp()
df_data['Square_X'] = np.square(df_data['X'])
df_data['Exp_Z'] = np.exp(df_data['Z'])
print("DataFrame with extra NumPy transforms:\n", df_data)

Column Means (NumPy): [16.8 37.8 14.8]
Column Medians (NumPy): [16. 41. 12.]
DataFrame with extra NumPy transforms:
     X   Y   Z  Square_X         Exp_Z
0  39  41   7      1521  1.096633e+03
1  18  46  32       324  7.896296e+13
2   4  44  12        16  1.627548e+05
3   7  38  14        49  1.202604e+06
4  16  20   9       256  8.103084e+03


In [192]:
# PROCEDURE 9: Importing and Summarizing Data Using Pandas

import numpy as np
import pandas as pd

# Step 1: Save the DataFrame to a CSV file
data = np.random.randint(1, 50, size=(5, 3))
df_data = pd.DataFrame(data, columns=['X', 'Y', 'Z'])
df_data.to_csv('sample_data.csv', index=False)
print("Data saved to 'sample_data.csv'.")

# Step 2: Load the CSV file back into a new DataFrame
df_imported = pd.read_csv('sample_data.csv')
print("Imported DataFrame:\n", df_imported)

# Step 3: Generate summary statistics
summary_stats = df_imported.describe()
print("Summary Statistics:\n", summary_stats)

# Step 4: Display column means and standard deviations
print("Column Means:\n", df_imported.mean())
print("Column Standard Deviations:\n", df_imported.std())

Data saved to 'sample_data.csv'.
Imported DataFrame:
     X   Y   Z
0  10  19  22
1  27  44   8
2  40  37  48
3  14  16  15
4  12  30   5
Summary Statistics:
                X          Y          Z
count   5.000000   5.000000   5.000000
mean   20.600000  29.200000  19.600000
std    12.720063  11.819475  17.184295
min    10.000000  16.000000   5.000000
25%    12.000000  19.000000   8.000000
50%    14.000000  30.000000  15.000000
75%    27.000000  37.000000  22.000000
max    40.000000  44.000000  48.000000
Column Means:
 X    20.6
Y    29.2
Z    19.6
dtype: float64
Column Standard Deviations:
 X    12.720063
Y    11.819475
Z    17.184295
dtype: float64


In [193]:
# TRY IT - Procedure 9

import pandas as pd

df_imported = pd.read_csv('sample_data.csv')

# Add a new calculated column
df_imported['Sum_XY'] = df_imported['X'] + df_imported['Y']
print("DataFrame with Sum_XY:\n", df_imported)

# Save the modified DataFrame to a new CSV file
df_imported.to_csv('sample_data_modified.csv', index=False)
print("Modified data saved to 'sample_data_modified.csv'.")

# Review the saved file
df_review = pd.read_csv('sample_data_modified.csv')
print("Reviewed Modified CSV:\n", df_review)

DataFrame with Sum_XY:
     X   Y   Z  Sum_XY
0  10  19  22      29
1  27  44   8      71
2  40  37  48      77
3  14  16  15      30
4  12  30   5      42
Modified data saved to 'sample_data_modified.csv'.
Reviewed Modified CSV:
     X   Y   Z  Sum_XY
0  10  19  22      29
1  27  44   8      71
2  40  37  48      77
3  14  16  15      30
4  12  30   5      42


In [194]:
import pandas as pd
df_kaggle = pd.read_csv('survey_results_public.csv')
print(df_kaggle.columns.tolist())

['ResponseId', 'Q120', 'MainBranch', 'Age', 'Employment', 'RemoteWork', 'CodingActivities', 'EdLevel', 'LearnCode', 'LearnCodeOnline', 'LearnCodeCoursesCert', 'YearsCode', 'YearsCodePro', 'DevType', 'OrgSize', 'PurchaseInfluence', 'TechList', 'BuyNewTool', 'Country', 'Currency', 'CompTotal', 'LanguageHaveWorkedWith', 'LanguageWantToWorkWith', 'DatabaseHaveWorkedWith', 'DatabaseWantToWorkWith', 'PlatformHaveWorkedWith', 'PlatformWantToWorkWith', 'WebframeHaveWorkedWith', 'WebframeWantToWorkWith', 'MiscTechHaveWorkedWith', 'MiscTechWantToWorkWith', 'ToolsTechHaveWorkedWith', 'ToolsTechWantToWorkWith', 'NEWCollabToolsHaveWorkedWith', 'NEWCollabToolsWantToWorkWith', 'OpSysPersonal use', 'OpSysProfessional use', 'OfficeStackAsyncHaveWorkedWith', 'OfficeStackAsyncWantToWorkWith', 'OfficeStackSyncHaveWorkedWith', 'OfficeStackSyncWantToWorkWith', 'AISearchHaveWorkedWith', 'AISearchWantToWorkWith', 'AIDevHaveWorkedWith', 'AIDevWantToWorkWith', 'NEWSOSites', 'SOVisitFreq', 'SOAccount', 'SOPartFr

In [195]:
# PROCEDURE 10: Data Grouping and Aggregation

import numpy as np
import pandas as pd

# Step 1: Load the Stack Overflow 2023 Developer Survey dataset
df_kaggle = pd.read_csv('survey_results_public.csv')
print("Loaded Dataset:\n", df_kaggle.head())

# Step 2: Select relevant columns
df_subset = df_kaggle[['Country', 'EdLevel', 'YearsCodePro', 'ConvertedCompYearly']]
print("Subset of Data:\n", df_subset.head())

# Step 3: Clean the data by dropping rows with missing values
df_clean = df_subset.dropna().copy()
print("Cleaned Data:\n", df_clean.head())

# Step 4: Categorize experience into groups (convert to numeric first)
df_clean['YearsCodePro'] = pd.to_numeric(df_clean['YearsCodePro'], errors='coerce')
df_clean = df_clean.dropna(subset=['YearsCodePro'])
df_clean['ExperienceLevel'] = np.where(df_clean['YearsCodePro'] >= 10, 'Senior', 'Junior')

# Step 5: Group data by Country and ExperienceLevel, compute average salary
grouped_data = df_clean.groupby(
    ['Country', 'ExperienceLevel']
)['ConvertedCompYearly'].mean()
print("Grouped Average Salary:\n", grouped_data.head())

# Step 6: Reset index for readability
grouped_data = grouped_data.reset_index()
print("Formatted Grouped Data:\n", grouped_data.head())

Loaded Dataset:
    ResponseId     Q120                      MainBranch              Age  \
0           1  I agree                   None of these  18-24 years old   
1           2  I agree  I am a developer by profession  25-34 years old   
2           3  I agree  I am a developer by profession  45-54 years old   
3           4  I agree  I am a developer by profession  25-34 years old   
4           5  I agree  I am a developer by profession  25-34 years old   

                                          Employment  \
0                                                NaN   
1                                Employed, full-time   
2                                Employed, full-time   
3                                Employed, full-time   
4  Employed, full-time;Independent contractor, fr...   

                             RemoteWork  \
0                                   NaN   
1                                Remote   
2  Hybrid (some remote, some in-person)   
3  Hybrid (some remote,

In [196]:
# TRY IT - Procedure 10

import numpy as np
import pandas as pd

# Re-load and clean dataset
df_kaggle = pd.read_csv('survey_results_public.csv')
df_subset = df_kaggle[['Country', 'EdLevel', 'YearsCodePro', 'ConvertedCompYearly']].dropna()

# Change grouping to EdLevel
grouped_by_ed = df_subset.groupby('EdLevel')['ConvertedCompYearly'].median()
print("Median Salary by Education Level:\n", grouped_by_ed)

# Compute median and standard deviation
grouped_stats = df_subset.groupby('EdLevel')['ConvertedCompYearly'].agg(['median', 'std'])
print("Median and Std by EdLevel:\n", grouped_stats)

# Top 10 countries with the highest average compensation
top10_countries = (
    df_subset.groupby('Country')['ConvertedCompYearly']
    .mean()
    .sort_values(ascending=False)
    .head(10)
)
print("Top 10 Countries by Average Compensation:\n", top10_countries)

Median Salary by Education Level:
 EdLevel
Associate degree (A.A., A.S., etc.)                                                   72000.0
Bachelor’s degree (B.A., B.S., B.Eng., etc.)                                          79556.0
Master’s degree (M.A., M.S., M.Eng., MBA, etc.)                                       74963.0
Primary/elementary school                                                             55764.0
Professional degree (JD, MD, Ph.D, Ed.D, etc.)                                        80690.0
Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)    56757.0
Some college/university study without earning a degree                                69608.0
Something else                                                                        56514.5
Name: ConvertedCompYearly, dtype: float64
Median and Std by EdLevel:
                                                      median           std
EdLevel                                                      

THE END OF PROCEDURES FOR LAB 6

START OF DATA AND OBSERVATION FOR LAB 6: CODE SNIPPET

In [197]:
# SNIPPET 1
import numpy as np

STUDENT_NAME = "Jesier Cresencio"
STUDENT_ID = 2043

np.random.seed(STUDENT_ID)
data = np.random.randint(1, STUDENT_ID % 100 + 50, size=10)
print(f"Jesier Cresencio's Array:", data)

mean_val = np.mean(data)
std_val = np.std(data)
print("Mean:", mean_val, "Std Dev:", std_val)

Jesier Cresencio's Array: [51 62 25 10 89 80 76 81 17 58]
Mean: 54.9 Std Dev: 27.094095297684326


In [198]:
# SNIPPET 2
import numpy as np

STUDENT_NAME = "Jesier Cresencio"
STUDENT_ID = 2043

np.random.seed(STUDENT_ID)
matrix = np.random.randint(1, STUDENT_ID % 50 + 20, size=(3, 4))
print(f"Jesier Cresencio's Matrix:\n", matrix)

row_sums = np.sum(matrix, axis=1)
col_sums = np.sum(matrix, axis=0)
print("Row sums:", row_sums)
print("Column sums:", col_sums)

Jesier Cresencio's Matrix:
 [[51 62 44 25]
 [10 25 58 16]
 [61 12 17 17]]
Row sums: [182 109 107]
Column sums: [122  99 119  58]


In [199]:
# SNIPPET 3
import numpy as np

STUDENT_NAME = "Jesier Cresencio"
STUDENT_ID = 252043

np.random.seed(STUDENT_ID)
arr3d = np.random.randint(0, STUDENT_ID % 20 + 10, size=(3, 3, 3))
print(f"Jesier Cresencio's 3D Array:\n", arr3d)

slice_mid = arr3d[:, 1, :]
print("Slice[:,1,:]:\n", slice_mid)

Jesier Cresencio's 3D Array:
 [[[ 0  5  4]
  [ 2  0  0]
  [ 9 12  1]]

 [[ 7  3  6]
  [11 11  2]
  [ 3 11  8]]

 [[ 1  8  1]
  [ 0  3  4]
  [ 6  8  6]]]
Slice[:,1,:]:
 [[ 2  0  0]
 [11 11  2]
 [ 0  3  4]]


In [200]:
# SNIPPET 4
import numpy as np

STUDENT_NAME = "Jesier Cresencio"
STUDENT_ID = 252043

np.random.seed(STUDENT_ID)
x = np.random.randint(1, STUDENT_ID % 100 + 50, size=10)
filtered = x[(x > STUDENT_ID % 50) & (x < STUDENT_ID % 100)]
print(f"Jesier Cresencio's Original:", x)
print("Filtered subset:", filtered)

Jesier Cresencio's Original: [54 62 33 65 10 13  8 68 46  7]
Filtered subset: []


In [201]:
# SNIPPET 5
import numpy as np

STUDENT_NAME = "Jesier Cresencio"
STUDENT_ID = 252043

np.random.seed(STUDENT_ID)
A = np.random.randint(1, STUDENT_ID % 50 + 20, size=(2, 2))
B = np.random.randint(1, STUDENT_ID % 50 + 20, size=(2, 2))
print("Matrix A:\n", A)
print("Matrix B:\n", B)

product = A @ B
det_A = np.linalg.det(A)
print("A @ B:\n", product)
print("Determinant of A:", det_A)

Matrix A:
 [[33 54]
 [62 37]]
Matrix B:
 [[51 33]
 [ 1 10]]
A @ B:
 [[1737 1629]
 [3199 2416]]
Determinant of A: -2127.0000000000005


In [202]:
# SNIPPET 6
import numpy as np

STUDENT_NAME = "Jesier Cresencio"
STUDENT_ID = 252043

angles = np.linspace(0, 2 * np.pi, 8)
sine_vals = np.sin(angles)
cos_vals = np.cos(angles)
print(f"Jesier Cresencio's Angles:", angles)
print("Sine:", sine_vals)
print("Cosine:", cos_vals)

Jesier Cresencio's Angles: [0.         0.8975979  1.7951958  2.6927937  3.5903916  4.48798951
 5.38558741 6.28318531]
Sine: [ 0.00000000e+00  7.81831482e-01  9.74927912e-01  4.33883739e-01
 -4.33883739e-01 -9.74927912e-01 -7.81831482e-01 -2.44929360e-16]
Cosine: [ 1.          0.6234898  -0.22252093 -0.90096887 -0.90096887 -0.22252093
  0.6234898   1.        ]


In [203]:
# SNIPPET 7
import numpy as np

STUDENT_NAME = "Jesier Cresencio"
STUDENT_ID = 252043

np.random.seed(STUDENT_ID)
arr = np.random.randint(1, STUDENT_ID % 50 + 20, size=(4, 4))
arr[::2, ::2] = 0
print(f"Jesier Cresencio's Modified 4x4 Array:\n", arr)

Jesier Cresencio's Modified 4x4 Array:
 [[ 0 54  0 37]
 [51 33  1 10]
 [ 0 50  0  4]
 [46  7 60 60]]


In [204]:
# SNIPPET 8
import numpy as np

STUDENT_NAME = "Jesier Cresencio"
STUDENT_ID = 252043

np.random.seed(STUDENT_ID)
scores = np.random.randint(0, STUDENT_ID % 100 + 50, 10)
grades = np.where(scores >= STUDENT_ID % 70, 'Pass', 'Fail')
print(f"Jesier Cresencio's Scores:", scores)
print("Grades:", grades)

Jesier Cresencio's Scores: [53 61 32 64  9 12  7 67 45  6]
Grades: ['Pass' 'Pass' 'Fail' 'Pass' 'Fail' 'Fail' 'Fail' 'Pass' 'Pass' 'Fail']


In [205]:
# SNIPPET 9
import numpy as np

STUDENT_NAME = "Jesier Cresencio"
STUDENT_ID = 252043

np.random.seed(STUDENT_ID)
arr = np.random.randint(1, STUDENT_ID % 50 + 20, size=(3, 4))
flat_arr = arr.flatten()
transposed_arr = arr.T
print("Original array:\n", arr)
print("Flattened:", flat_arr)
print("Transposed:\n", transposed_arr)

Original array:
 [[33 54 62 37]
 [51 33  1 10]
 [13 50  8  4]]
Flattened: [33 54 62 37 51 33  1 10 13 50  8  4]
Transposed:
 [[33 51 13]
 [54 33 50]
 [62  1  8]
 [37 10  4]]


In [206]:
# SNIPPET 10
import numpy as np

STUDENT_NAME = "Jesier Cresencio"
STUDENT_ID = 252043

np.random.seed(STUDENT_ID)
arr = np.random.randint(1, STUDENT_ID % 50 + 20, (3, 3))
mask = arr % 2 == 0
arr[mask] = -1
print("Array with conditional replacements:\n", arr)

Array with conditional replacements:
 [[33 -1 -1]
 [37 51 33]
 [ 1 -1 13]]


In [207]:
# SNIPPET 11
import numpy as np
import pandas as pd

STUDENT_NAME = "Jesier Cresencio"
STUDENT_ID = 252043

np.random.seed(STUDENT_ID)
df = pd.DataFrame({
    'Name': [STUDENT_NAME] * 5,
    'Score': np.random.randint(STUDENT_ID % 50, STUDENT_ID % 100 + 50, 5),
    'YearsCodePro': np.random.randint(0, STUDENT_ID % 20 + 10, 5)
})
print(df)

               Name  Score  YearsCodePro
0  Jesier Cresencio     75            12
1  Jesier Cresencio     79             1
2  Jesier Cresencio     75             7
3  Jesier Cresencio     43             3
4  Jesier Cresencio     52             6


In [208]:
# SNIPPET 12
import numpy as np
import pandas as pd

STUDENT_NAME = "Jesier Cresencio"
STUDENT_ID = 252043

np.random.seed(STUDENT_ID)
df = pd.DataFrame({
    'EdLevel': ['Bachelor', 'Master', 'PhD', 'Bachelor', 'Master'],
    'ConvertedComp': np.random.randint(40000, 150000, 5)
})
avg_salary = df.groupby('EdLevel')['ConvertedComp'].mean()
print(avg_salary)

EdLevel
Bachelor    87699.5
Master      95038.5
PhD         55076.0
Name: ConvertedComp, dtype: float64


In [209]:
# SNIPPET 13
import numpy as np
import pandas as pd

STUDENT_NAME = "Jesier Cresencio"
STUDENT_ID = 252043

np.random.seed(STUDENT_ID)
df = pd.DataFrame({
    'Country': ['Philippines', 'USA', 'UK', 'Canada', 'Germany'],
    'ConvertedComp': np.random.randint(40000, 150000, 5)
})
top5 = df.sort_values(by='ConvertedComp', ascending=False)
print(top5)

       Country  ConvertedComp
1          USA         108669
0  Philippines          96629
4      Germany          81408
3       Canada          78770
2           UK          55076


In [210]:
# SNIPPET 14
import numpy as np
import pandas as pd

STUDENT_NAME = "Jesier Cresencio"
STUDENT_ID = 252043

np.random.seed(STUDENT_ID)
df = pd.DataFrame({
    'Name': [STUDENT_NAME] * 5,
    'YearsCodePro': np.random.randint(0, STUDENT_ID % 20 + 10, 5)
})
high_exp = df[df['YearsCodePro'] > STUDENT_ID % 10]
print(high_exp)

               Name  YearsCodePro
1  Jesier Cresencio             5
2  Jesier Cresencio             4


In [211]:
# SNIPPET 15
import numpy as np
import pandas as pd

STUDENT_NAME = "Jesier Cresencio"
STUDENT_ID = 252043

np.random.seed(STUDENT_ID)
df = pd.DataFrame({
    'ConvertedComp': np.random.randint(40000, 150000, 5)
})
bins = [0, 50000, 100000, 150000, 200000]
labels = ['0-50k', '50-100k', '100-150k', '>150k']
df['Bracket'] = pd.cut(df['ConvertedComp'], bins=bins, labels=labels)
print(df)

   ConvertedComp   Bracket
0          96629   50-100k
1         108669  100-150k
2          55076   50-100k
3          78770   50-100k
4          81408   50-100k


In [212]:
# SNIPPET 16
import numpy as np
import pandas as pd

STUDENT_NAME = "Jesier Cresencio"
STUDENT_ID = 252043

np.random.seed(STUDENT_ID)
df = pd.DataFrame({
    'ConvertedComp': np.random.randint(40000, 150000, 5)
})
df['LogComp'] = np.log(df['ConvertedComp'])
print(df)

   ConvertedComp    LogComp
0          96629  11.478634
1         108669  11.596062
2          55076  10.916469
3          78770  11.274287
4          81408  11.307229


In [213]:
# SNIPPET 17
import numpy as np
import pandas as pd

STUDENT_NAME = "Jesier Cresencio"
STUDENT_ID = 252043

np.random.seed(STUDENT_ID)
df = pd.DataFrame({
    'YearsCodePro': np.random.randint(0, STUDENT_ID % 20 + 10, 5),
    'ConvertedComp': np.random.randint(40000, 150000, 5)
})
corr_matrix = df.corr()
print(corr_matrix)

               YearsCodePro  ConvertedComp
YearsCodePro       1.000000      -0.319171
ConvertedComp     -0.319171       1.000000


In [214]:
# SNIPPET 18
import numpy as np
import pandas as pd

STUDENT_NAME = "Jesier Cresencio"
STUDENT_ID = 252043

np.random.seed(STUDENT_ID)
df = pd.DataFrame({
    'EdLevel': ['Bachelor', 'Master', 'PhD', 'Bachelor', 'Master'],
    'ConvertedComp': np.random.randint(40000, 150000, 5)
})
summary = df.groupby('EdLevel')['ConvertedComp'].agg(
    ['mean', 'median', 'std']
).reset_index()
print(summary)

    EdLevel     mean   median           std
0  Bachelor  87699.5  87699.5  12628.220005
1    Master  95038.5  95038.5  19276.437962
2       PhD  55076.0  55076.0           NaN


In [215]:
# SNIPPET 19
import numpy as np
import pandas as pd

STUDENT_NAME = "Jesier Cresencio"
STUDENT_ID = 252043

np.random.seed(STUDENT_ID)
df = pd.DataFrame({
    'ConvertedComp': np.random.randint(40000, 150000, 5)
})
threshold = 110000
df['HighPay'] = np.where(df['ConvertedComp'] > threshold, 'Yes', 'No')
print(df)

   ConvertedComp HighPay
0          96629      No
1         108669      No
2          55076      No
3          78770      No
4          81408      No


In [216]:
# SNIPPET 20
import numpy as np
import pandas as pd

STUDENT_NAME = "Jesier Cresencio"
STUDENT_ID = 252043

np.random.seed(STUDENT_ID)
df = pd.DataFrame({
    'Country': ['Philippines', 'USA', 'UK', 'Canada', 'Germany'],
    'ConvertedComp': np.random.randint(40000, 150000, 5)
})
top_countries = df.groupby('Country')['ConvertedComp'].agg(['mean', 'max'])
print(top_countries)

                 mean     max
Country                      
Canada        78770.0   78770
Germany       81408.0   81408
Philippines   96629.0   96629
UK            55076.0   55076
USA          108669.0  108669


THE END OF DATA AND OBSERVATION PART OF LAB 6

THE END OF CRESENCIO'S LAB 6: NUMERICAL AND DATA ANALYSIS WITH NUMPY AND PANDAS